### ISSUE TITLE
Smote(TOMEK), determining n neighbors

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [SupervisedStylometry/SuperStyl#21]
```
Traceback (most recent call last):
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 211, in __call__
    return self.function(*args, **kwargs)
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 1045, in _fit_and_predict
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/imblearn/pipeline.py", line 262, in fit
    Xt, yt = self._fit(X, y, **fit_params_steps)
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/imblearn/pipeline.py", line 220, in _fit
    X, y, fitted_transformer = fit_resample_one_cached(
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/joblib/memory.py", line 349, in __call__
    return self.func(*args, **kwargs)
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/imblearn/pipeline.py", line 388, in _fit_resample_one
    X_res, y_res = sampler.fit_resample(X, y, **fit_params)
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/imblearn/base.py", line 83, in fit_resample
    output = self._fit_resample(X, y)
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/imblearn/over_sampling/_smote/base.py", line 309, in _fit_resample
    nns = self.nn_k_.kneighbors(X_class, return_distance=False)[:, 1:]
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/sklearn/neighbors/_base.py", line 724, in kneighbors
    raise ValueError(
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6
"""
```

**Comment by Jean-Baptiste-Camps** [comment]
https://stackoverflow.com/questions/49395939/smote-initialisation-expects-n-neighbors-n-samples-but-n-samples-n-neighbo

**Comment by Jean-Baptiste-Camps** [comment]
But first, find out why that happens on cases where they SHOULD BE more than five samples per class.

**Comment by Jean-Baptiste-Camps** [comment]
```
Traceback (most recent call last):
  File "train_svm.py", line 53, in <module>
    svm = superstyl.svm.train_svm(train, test, cross_validate=args.cross_validate, k=args.k, dim_reduc=args.dim_reduc,
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/superstyl/svm.py", line 147, in train_svm
    preds = skmodel.cross_val_predict(pipe, train, classes, cv=myCV, verbose=1, n_jobs=-1)
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 963, in cross_val_predict
    predictions = parallel(
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/jbcamps/Data/F/Stylometrie/SuperStyl/env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6
```

**Comment by Jean-Baptiste-Camps** [comment]
This is a duplicate of #12 … Keeping only this one.

**Comment by Jean-Baptiste-Camps** [comment]
Should implement some of the solutions of accepted stack answer.

**Comment by Jean-Baptiste-Camps** [comment]
Apparently, it isn't solved. I'm reopening this.

**Comment by TheoMoins** [comment]
To cite JB : 
> "le problème vient peut-être de la validation croisée, Quand tu fais du group-k-fold, tu peux te retrouver avec un nombre de neighbours qui, pour une itération donnée, va être insuffisant" 

So we have to compute the number of neighbors depending on the cross validation we do. For the group k fold case, the value depend on the minimal group size, which I don't really look at how to compute, so I gave another approxiamtion

**Comment by TheoMoins** [comment]
NB : if k=2, a training fold can contain all samples of a class, and SMOTE fail as at least 2 classes are needed

**Comment by TheoMoins** [comment]
The commit 5b38163ed52b6365fa7b692577b59eae69c573ef solve the issue
